import fixture from "../../../bench/fixtures/samsung_is.json";

export const revenue = ["2023", "2022"].map((period) =>
  fixture.rows.find((row) => row.label === "매출액" && row.period === period),
);
export const fragment = ["매출액", "매출원가", "매출총이익"].map((label) => ({
  label,
  values: ["2023", "2022"].map(
    (period) =>
      fixture.rows.find((row) => row.label === label && row.period === period)
        .value,
  ),
}));
const current = BigInt(revenue[0].value);
const prior = BigInt(revenue[1].value);
const difference = current - prior;
// Half-up rounding in integer arithmetic; display never becomes an operand.
const rounded = (numerator, denominator) =>
  (numerator * 2n + denominator) / (denominator * 2n);
export const percentage = `−${Number(rounded(-difference * 1000n, prior)) / 10}`;
export const exactPercentage = `−${Number(rounded(-difference * 10000n, prior)) / 100}`;
export const formatOriginal = (value) => BigInt(value).toLocaleString("en-US");
export const displayValue = (row, lang) =>
  `${Number(rounded(BigInt(row.value) * 10n, 1000000n)) / 10}${lang === "ko" ? "조원" : " trillion KRW"}`;
export const dictionary = {
  ko: {
    prototype: "정적 디자인 시안",
    prototypeDetail: "실제 공시 수치 · 실행 기록 아님",
    new: "새 조사",
    history: "기록",
    settings: "설정",
    close: "닫기",
    title: "삼성전자 연간 매출 비교",
    company: "삼성전자",
    eyebrow: "연간 비교",
    question: "삼성전자 2023년 매출액을 2022년과 비교해 줘.",
    questionLabel: "질문",
    answer: "전년보다 매출액이 감소했습니다.",
    answerLabel: "답변",
    metric: "매출액",
    revenue: "Revenue (매출액)",
    delta: "전년 대비 증감률",
    calc: "계산됨",
    formula: "계산 근거",
    formulaNote: "원문 수치로 계산한 뒤 표시값을 반올림합니다.",
    inputs: "계산에 사용한 공시",
    period: "회계연도",
    value: "매출액",
    source: "근거",
    reported: "공시 수치",
    report: "연결감사보고서",
    comparison: "2023 / 2022 · 연결 기준",
    explanation: "설명 더 보기",
    explanationText:
      "두 연도의 연결 매출액을 같은 원문 단위로 비교했습니다. 증감률은 전년도 매출액을 기준으로 계산합니다.",
    limitation:
      "표시값은 반올림했습니다. 사업상 원인은 이 비교에 포함하지 않습니다.",
    limits: "비교 범위",
    trail: "확인 경로",
    trailNote: "단계 구성 예시 · 실행 시간 미측정",
    stages: ["질문 해석", "공시 찾기", "수치 확인", "계산", "답변 작성"],
    stageTarget: "연결손익계산서 · 매출액",
    evidence: "공시 근거",
    selected: "선택한 수치",
    excerpt: "원문 발췌",
    excerptNote: "연결손익계산서 일부 · 백만원",
    excerptTitle: "연 결 손 익 계 산 서",
    excerptCompany: "삼성전자주식회사와 그 종속기업",
    metadata: "삼성전자 · 2023년 연결감사보고서",
    basis: "연결",
    units: "백만원",
    reconciliation: "원문과 표시 단위",
    rounding: "조원 단위 · 소수 첫째 자리 반올림",
    openSource: "감사보고서 원문 열기 ↗",
    sourceNote:
      "삼성전자 IR 제공 PDF · 본문 10쪽. 해당 페이지 바로가기는 미검증입니다.",
    translate: "번역 보기",
    translated: "번역 · 원문은 위에 유지됩니다",
    prompt: "다음 질문을 입력하세요",
    context: "다음 질문의 확정 문맥",
    contextChanged: "변경된 기간",
    send: "질문 보내기",
    promptHint: "Enter 전송 · Shift + Enter 줄바꿈",
    staticError:
      "정적 시안에서는 새 질문을 실행하지 않습니다. 입력한 질문은 유지됩니다.",
    expand: "펼치기",
    collapse: "접기",
    footnote: "공시를 읽고, 근거를 확인하는 작업 공간",
    light: "라이트",
    dark: "다크",
    theme: "테마",
    language: "언어",
    runtime: "정적 시안 · 모델 연결 없음",
    historyTitle: "최근 조사",
    historyNote: "이 시안에 포함된 조사",
    reopen: "이 조사 열기",
    newTitle: "새 조사",
    newNote:
      "새 질문을 작성할 수 있습니다. 실제 실행은 포함하지 않은 디자인 시안입니다.",
    draft: "질문 작성하기",
    editingContext: "확정 문맥",
    contextNote: "시안은 삼성전자 연간 매출 비교로 고정되어 있습니다.",
  },
  en: {
    prototype: "Static design study",
    prototypeDetail: "Reported figures · not an execution recording",
    new: "New investigation",
    history: "History",
    settings: "Settings",
    close: "Close",
    title: "Samsung annual revenue comparison",
    company: "Samsung Electronics",
    eyebrow: "Annual comparison",
    question: "Compare Samsung’s revenue in 2023 with 2022.",
    questionLabel: "Question",
    answer: "Revenue decreased from the previous year.",
    answerLabel: "Answer",
    metric: "Revenue",
    revenue: "Revenue (매출액)",
    delta: "Year-over-year change",
    calc: "calc",
    formula: "Show your work",
    formulaNote: "Calculated from original values, then rounded for display.",
    inputs: "Source inputs",
    period: "Fiscal year",
    value: "Revenue",
    source: "Evidence",
    reported: "Reported",
    report: "Consolidated audit report",
    comparison: "2023 / 2022 · Consolidated",
    explanation: "Read explanation",
    explanationText:
      "Consolidated revenue is compared in the same source unit across both years. The percentage change uses the previous year’s revenue as its baseline.",
    limitation:
      "Display values are rounded. This comparison does not explain business causes.",
    limits: "Comparison scope",
    trail: "Evidence trail",
    trailNote: "Illustrative stages · execution time not measured",
    stages: [
      "Interpret question",
      "Find report",
      "Check figures",
      "Calculate",
      "Write answer",
    ],
    stageTarget: "Consolidated income statement · Revenue",
    evidence: "Filing evidence",
    selected: "Selected figure",
    excerpt: "Original excerpt",
    excerptNote: "Income statement fragment · KRW millions",
    excerptTitle: "연 결 손 익 계 산 서",
    excerptCompany: "삼성전자주식회사와 그 종속기업",
    metadata: "Samsung · 2023 consolidated audit report",
    basis: "Consolidated",
    units: "KRW millions",
    reconciliation: "Source and display units",
    rounding: "KRW trillions · rounded to one decimal",
    openSource: "Open original audit report ↗",
    sourceNote:
      "Samsung IR PDF · printed page 10. A direct page link has not been verified.",
    translate: "Show translation",
    translated: "Translation · original retained above",
    prompt: "Ask a follow-up question",
    context: "Confirmed context for your next question",
    contextChanged: "Changed period",
    send: "Send question",
    promptHint: "Enter to send · Shift + Enter for a new line",
    staticError:
      "This static study cannot run new questions. Your draft is preserved.",
    expand: "Expand",
    collapse: "Collapse",
    footnote: "A workspace for reading filings and checking evidence",
    light: "Light",
    dark: "Dark",
    theme: "Theme",
    language: "Language",
    runtime: "Static study · no model connected",
    historyTitle: "Recent investigations",
    historyNote: "Included in this design study",
    reopen: "Open investigation",
    newTitle: "New investigation",
    newNote:
      "You can compose a question. This design study does not include live execution.",
    draft: "Compose question",
    editingContext: "Confirmed context",
    contextNote: "This study is fixed to Samsung’s annual revenue comparison.",
  },
};
