export const params=new URLSearchParams(location.search);
export const variant=Math.min(5,Math.max(1,Number(params.get('v'))||1));
export let language=['ko','en'].includes(params.get('lang'))?params.get('lang'):(localStorage.getItem('filing-mock-language')||(navigator.language.startsWith('ko')?'ko':'en'));
export function setup(onLanguage){document.body.dataset.v=variant;document.documentElement.lang=language;document.body.dataset.theme=localStorage.getItem('filing-mock-theme')||(matchMedia('(prefers-color-scheme:dark)').matches?'dark':'light');const header=document.querySelector('.site-header');header.insertAdjacentHTML('beforeend',`<div class="language-switch" role="group" aria-label="Language"><button data-lang="ko" aria-pressed="${language==='ko'}">한국어</button><button data-lang="en" aria-pressed="${language==='en'}">English</button></div><button class="theme-control"></button>`);
function themeLabel(){document.querySelector('.theme-control').textContent=document.body.dataset.theme==='dark'?(language==='ko'?'밝게':'Light'):(language==='ko'?'어둡게':'Dark')}
function change(next){const sections=[...document.querySelectorAll('main section[id]')];const threshold=header.getBoundingClientRect().bottom+40;const anchor=sections.filter(s=>s.getBoundingClientRect().top<=threshold).at(-1);language=next;document.documentElement.lang=next;localStorage.setItem('filing-mock-language',next);document.querySelectorAll('[data-lang]').forEach(b=>b.setAttribute('aria-pressed',b.dataset.lang===next));const u=new URL(location);u.searchParams.set('lang',next);history.replaceState(null,'',u);onLanguage(next);themeLabel();if(anchor&&anchor.id!=='top'){requestAnimationFrame(()=>requestAnimationFrame(()=>{const target=scrollY+anchor.getBoundingClientRect().top-header.getBoundingClientRect().height-16;scrollTo({top:target,behavior:'instant'})}))}parent.postMessage({type:'language',lang:next},location.origin)}
document.querySelectorAll('[data-lang]').forEach(b=>b.onclick=()=>change(b.dataset.lang));document.querySelector('.theme-control').onclick=()=>{document.body.dataset.theme=document.body.dataset.theme==='dark'?'light':'dark';localStorage.setItem('filing-mock-theme',document.body.dataset.theme);themeLabel()};themeLabel();onLanguage(language);
document.addEventListener('keydown',e=>{if(/^(INPUT|TEXTAREA|SELECT)$/.test(e.target.tagName)||e.target.isContentEditable||e.metaKey||e.ctrlKey||e.altKey)return;if(parent===window)return;if(e.key==='ArrowLeft'||e.key==='ArrowRight'){parent.postMessage({type:'variant',delta:e.key==='ArrowRight'?1:-1},location.origin)}else if(/^[1-5]$/.test(e.key))parent.postMessage({type:'selectVariant',index:Number(e.key)-1},location.origin)});
}
export const pair=(ko,en)=>language==='ko'?ko:en;
